version: '3.8'

services:
  # --- Backend API ---
  backend:
    build: ./backend
    container_name: kadmill_backend
    ports:
      - "3333:3333"
    environment:
      # --- BANCO DE DADOS (Mantemos no Railway, pois funcionou) ---
      DATABASE_URL: "postgresql://postgres:IKWzKGEgQwahWaFrZjMnArStoMkkwuSH@turntable.proxy.rlwy.net:18883/railway"
      
      # --- REDIS (Mudamos para LOCAL - Container abaixo) ---
      REDIS_HOST: "redis"  # Nome do serviço abaixo
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""   # Sem senha para local
      
      # Configurações da App
      PORT: 3333
      JWT_SECRET: "H0sT@lkq134./d2" 
      
      # Admin Bootstrap
      BOOTSTRAP_ADMIN_EMAIL: "kadmillAdminGeral@gmail.com"
      BOOTSTRAP_ADMIN_PASSWORD: "8j@LKmn#3"
    depends_on:
      - redis
    networks:
      - kadmill_network

  # --- [NOVO] Redis Local (Para fugir do bloqueio de rede) ---
  redis:
    image: redis:alpine
    container_name: kadmill_redis
    ports:
      - "6379:6379"
    networks:
      - kadmill_network

  # --- Frontend App ---
  frontend:
    build: ./frontend
    container_name: kadmill_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - kadmill_network

networks:
  kadmill_network:
    driver: bridge