version: '3.8'

services:
  # --- Backend API ---
  backend:
    build: ./backend
    env_file: .env
    ports:                 # <--- ADD THIS SECTION
      - "3333:3333"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=redis  # Alterado para coincidir com o nome do serviÃ§o abaixo
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - kadmill_network  # Adicionado para entrar na mesma rede do Redis

  # --- Redis Local ---
  redis:
    image: redis/redis-stack-server:latest
    container_name: kadmill_redis
    ports:
      - "6379:6379"
    networks:
      - kadmill_network

  # --- Frontend App ---
  frontend:
    build: ./frontend
    container_name: kadmill_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - kadmill_network

networks:
  kadmill_network:
    driver: bridge